import Header from '@/components/Header'
import TopCards2 from '@/components/TopCards2'
import BarChart from '@/components/BarChart'
import RecentMovs from '@/components/RecentMovs'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-gray-100 min-h-screen'>
                <Header teste="Texto"/>
                <TopCards2/>
                <div className='p-4 grid md:grid-cols-3 grid-cols-1 gp-4'>
                    <BarChart/>
                    <RecentMovs/>
                </div>
            </main>
        </>
    )
}
