import Header from '@/components/Header'
import Login from '@/components/Login'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-gray-100 min-h-screen'>
                <Header teste="Texto"/>
                
                <Login/>
                
            </main>
        </>
    )
}
